package com.petshop.view;

import com.petshop.controller.AgendamentoController;
import com.petshop.controller.PetController;
import com.petshop.controller.UsuarioController;
import com.petshop.dao.UsuarioDAO;
import com.petshop.model.Agendamento;
import com.petshop.model.Pet;
import com.petshop.model.Usuario;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import javax.swing.JOptionPane;

public class TelaMeuPerfilCliente extends javax.swing.JFrame {
    private UsuarioDAO usuarioDAO;
    private PetController petController;
    private AgendamentoController agendamentoController; 
    private Usuario usuario;
    private Usuario usuarioLogado;
    private UsuarioController usuarioController;

    public TelaMeuPerfilCliente(UsuarioDAO usuarioDAO, PetController petController, AgendamentoController agendamentoController, Usuario usuario, Usuario usuarioLogado, UsuarioController usuarioController) {
        initComponents();
        this.usuarioDAO = usuarioDAO;
        this.petController = petController;
        this.agendamentoController = agendamentoController; 
        this.usuario = usuario;
        this.usuarioLogado = usuarioLogado;
        this.jbNomeUsuario.setText(usuario.getNome());
        this.usuarioController = usuarioController;
        carregarPets(usuario);
        carregarAgendamentos(usuario);
    }

    private void carregarPets(Usuario usuario) {
        List<Pet> pets = petController.buscarPetsPorDono(usuario);
        DefaultTableModel modelo = (DefaultTableModel) tblMeusPets.getModel();
        modelo.setRowCount(0);

        for (Pet pet : pets) {
            modelo.addRow(new Object[]{
                pet.getNome(),
                pet.getRaca(),
                pet.getIdade(),
                pet.getSexo()
            });
        }
    }

    private void carregarAgendamentos(Usuario usuario) {
        List<Agendamento> agendamentos = agendamentoController.listarAgendamentosPorUsuario(usuario);
        DefaultTableModel modelo = (DefaultTableModel) tblMeusAgendamentos.getModel();
        modelo.setRowCount(0);

        for (Agendamento agendamento : agendamentos) {
            modelo.addRow(new Object[]{
                agendamento.getServico(),
                agendamento.getDataHora(),
                agendamento.getPet().getNome()
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        petshop = new javax.swing.JLabel();
        sejabemvindo = new javax.swing.JLabel();
        jbNomeUsuario = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnNovoAgendamento = new javax.swing.JButton();
        brnMeuPerfil = new javax.swing.JButton();
        btnEditarPerfil = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tabelaMeusPets = new javax.swing.JScrollPane();
        tblMeusPets = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMeusAgendamentos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel2.setBackground(new java.awt.Color(80, 161, 255));

        petshop.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        petshop.setForeground(new java.awt.Color(255, 255, 255));
        petshop.setText("PETSHOP");

        sejabemvindo.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        sejabemvindo.setForeground(new java.awt.Color(255, 255, 255));
        sejabemvindo.setText("Seja bem-vindo, ");

        jbNomeUsuario.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jbNomeUsuario.setForeground(new java.awt.Color(255, 51, 51));

        btnSair.setBackground(new java.awt.Color(255, 123, 123));
        btnSair.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSair.setForeground(new java.awt.Color(255, 255, 255));
        btnSair.setText("Sair");
        btnSair.setBorder(null);
        btnSair.setPreferredSize(new java.awt.Dimension(26, 17));
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(petshop, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(sejabemvindo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 239, Short.MAX_VALUE)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(petshop)
                    .addComponent(sejabemvindo)
                    .addComponent(jbNomeUsuario)
                    .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(241, 241, 241));
        jPanel3.setPreferredSize(new java.awt.Dimension(242, 481));

        btnNovoAgendamento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnNovoAgendamento.setForeground(new java.awt.Color(30, 255, 0));
        btnNovoAgendamento.setText("Novo Agendamento");
        btnNovoAgendamento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(30, 255, 0)));
        btnNovoAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoAgendamentoActionPerformed(evt);
            }
        });

        brnMeuPerfil.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        brnMeuPerfil.setForeground(new java.awt.Color(30, 255, 0));
        brnMeuPerfil.setText("Meu Perfil");
        brnMeuPerfil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(30, 255, 0)));

        btnEditarPerfil.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnEditarPerfil.setForeground(new java.awt.Color(30, 255, 0));
        btnEditarPerfil.setText("Editar Perfil");
        btnEditarPerfil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(30, 255, 0)));
        btnEditarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPerfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNovoAgendamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(brnMeuPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditarPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnNovoAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(brnMeuPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnEditarPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel4.setPreferredSize(new java.awt.Dimension(534, 482));

        jLabel1.setText("MEUS PETS");

        jLabel2.setText("MEUS AGENDAMENTOS");

        tblMeusPets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Raça", "Idade", "Sexo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaMeusPets.setViewportView(tblMeusPets);
        if (tblMeusPets.getColumnModel().getColumnCount() > 0) {
            tblMeusPets.getColumnModel().getColumn(0).setResizable(false);
            tblMeusPets.getColumnModel().getColumn(1).setResizable(false);
            tblMeusPets.getColumnModel().getColumn(2).setResizable(false);
            tblMeusPets.getColumnModel().getColumn(3).setResizable(false);
        }

        tblMeusAgendamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Serviço", "Data", "Pet"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblMeusAgendamentos);
        if (tblMeusAgendamentos.getColumnModel().getColumnCount() > 0) {
            tblMeusAgendamentos.getColumnModel().getColumn(0).setResizable(false);
            tblMeusAgendamentos.getColumnModel().getColumn(1).setResizable(false);
            tblMeusAgendamentos.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabelaMeusPets)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(189, 189, 189))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(tabelaMeusPets, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        int resposta = JOptionPane.showConfirmDialog(this, "Você tem certeza que deseja sair?", "Confirmar Saída", JOptionPane.YES_NO_OPTION);
        if (resposta == JOptionPane.YES_OPTION) {
            new TelaLogin(usuarioDAO, petController, agendamentoController).setVisible(true); 
            dispose();
        }
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnEditarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPerfilActionPerformed
         TelaDeEditarPerfilCliente telaEditarPerfil = new TelaDeEditarPerfilCliente(
            usuarioDAO,
            petController,
            agendamentoController,
            usuarioLogado,
            usuario,
            new TelaPrincipal(usuarioDAO, petController, agendamentoController, usuarioLogado), // Passar a tela principal correta
            usuarioController
        );
        telaEditarPerfil.setVisible(true);
        dispose();      
    }//GEN-LAST:event_btnEditarPerfilActionPerformed

    private void btnNovoAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoAgendamentoActionPerformed
       try {
            TelaAgendamentoCliente telaAgendamento = new TelaAgendamentoCliente(
                usuarioDAO,
                petController,
                new TelaPrincipal(usuarioDAO, petController, agendamentoController, usuarioLogado), // Passar a tela principal correta
                agendamentoController,
                usuarioController,
                usuarioLogado
            );
            telaAgendamento.setVisible(true);
            dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao abrir a tela de agendamento: " + e.getMessage());
        }   
    }//GEN-LAST:event_btnNovoAgendamentoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnMeuPerfil;
    private javax.swing.JButton btnEditarPerfil;
    private javax.swing.JButton btnNovoAgendamento;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jbNomeUsuario;
    private javax.swing.JLabel petshop;
    private javax.swing.JLabel sejabemvindo;
    private javax.swing.JScrollPane tabelaMeusPets;
    private javax.swing.JTable tblMeusAgendamentos;
    private javax.swing.JTable tblMeusPets;
    // End of variables declaration//GEN-END:variables
}
